### ISSUE TITLE
Empty DropDown 

### ISSUE THREAD

**Issue by Anavrin1990** [SolidAlloy/ClassTypeReference-for-Unity#21]
Hello!

I tried to add `[SerializeField] private TypeReference test` to MonoBehaviour with and without [Inherits] but dropDown is always empty =(

I tried 2.6.2 and 2.1.0 ver

Unity 2019.4 11 and 2020.1 8

macOS Big Sur

**Comment by Anavrin1990** [comment]
In Console 

<img width="1590" alt="Снимок экрана 2020-11-21 в 23 49 37" src="https://user-images.githubusercontent.com/25079982/99885089-53d0cd00-2c54-11eb-9587-fc636697bfce.png">

![image](https://user-images.githubusercontent.com/25079982/99885107-6cd97e00-2c54-11eb-99df-a2b398af26b6.png)

**Comment by Anavrin1990** [comment]
NullReference fixed by switch .NET to 4. But DropDown still empty =(

**Comment by Anavrin1990** [comment]
@SolidAlloy

**Comment by SolidAlloy** [comment]
Hi, sorry for the late response. I'll take a look at it today

**Comment by Anavrin1990** [comment]
Thanks!

**Comment by SolidAlloy** [comment]
It works without issues for me in versions 2019.4.11 and 2020.2.0 on Windows. I also tried switching between .NET 2.0 and 4.x, and it didn't cause any errors. I'm very surprised to see there is a difference in code execution on .NET 2.0 and 4.x, as nothing in the code should produce such an error.

Is your default assembly called Assembly-CSharp? If not, it can theoretically produce an empty drop-down.

Please try using 2.6.2 again and import Usage Samples from Package Manager. Open the Demo scene inside the sample and check if the drop-down menus are empty there too.

**Comment by Anavrin1990** [comment]
I used Samples and when I start project I saw this Warnings

And judging by Rider editor assembly called Assembly-CSharp

<img width="671" alt="Снимок экрана 2020-11-27 в 16 10 29" src="https://user-images.githubusercontent.com/25079982/100443212-14c6cf80-30cb-11eb-81d6-1c9cb3c7f7d1.png">

<img width="2628" alt="Снимок экрана 2020-11-27 в 15 45 23" src="https://user-images.githubusercontent.com/25079982/100443223-1abcb080-30cb-11eb-8772-50f95d194b43.png">

**Comment by Anavrin1990** [comment]
Hey! If add DropdownHeight = 300 it works, but place left, it is weird =D 

<img width="2560" alt="Снимок экрана 2020-11-27 в 16 26 43" src="https://user-images.githubusercontent.com/25079982/100444623-86a01880-30cd-11eb-9b3f-8b20b3cbdb34.png">

**Comment by Anavrin1990** [comment]
I think issue in DropDownWindow.AdjustSizeIfNeeded() Debug.Log(1) called once but Debug.Log(2) infinite loop before close DropDown.

![image](https://user-images.githubusercontent.com/25079982/100448170-b9e5a600-30d3-11eb-8130-e46d2019e38b.png)

**Comment by SolidAlloy** [comment]
Thanks for the debugging! I'll check what causes this behavior and get back to you

**Comment by Anavrin1990** [comment]
Thanks!

**Comment by Anavrin1990** [comment]
If windowSize.height == 0 ShowAsDropDown doesn't call OnGUI and DrawContent doesn't called too and doesn't calculate contentHeight

<img width="1495" alt="Снимок экрана 2020-11-27 в 17 59 26" src="https://user-images.githubusercontent.com/25079982/100452124-590d9c00-30da-11eb-9108-7941deabc49f.png">

<img width="1373" alt="Снимок экрана 2020-11-27 в 18 01 34" src="https://user-images.githubusercontent.com/25079982/100452278-9ffb9180-30da-11eb-990a-862d1e43647d.png">

**Comment by SolidAlloy** [comment]
I just pushed an update that fixes different DropdownWindow position issues. Please update ClassTypeReference to 2.6.3 and check how it works on your end. I didn't include your suggestion to change the window height to 1 pixel yet because the update to 2.6.3 may have already fixed it. But if it still doesn't work for you, I will include your fix too. In the end, it may really be a MacOS-specific issue.
The amount of work put into just showing a window in the right place is huge. I wish Unity made it easier :sweat:

**Comment by Anavrin1990** [comment]
I updated both dependencies and something went wrong =D

![image](https://user-images.githubusercontent.com/25079982/100468563-78b2bd80-30f6-11eb-8cf3-9225cff8f33b.png)

**Comment by Anavrin1990** [comment]
I replace EditorGUIUtility.GetMainWindowPosition() with Screen.currentResolution it fix this problem but DropDown still empty and onGUI doesn't called with zero height. And still in left corner =D

**Comment by Anavrin1990** [comment]
I added `windowHeight == 0 ? 1 : windowHeight` and `if (_contentHeight == 1f || Event.current.type == EventType.Repaint)
                    _contentHeight = contentHeight;` in `DrawContent()` it works.

Now by Y axis this work properly, but X axis on left =D

![image](https://user-images.githubusercontent.com/25079982/100470316-db598880-30f9-11eb-9883-5b79e752a91b.png)

**Comment by Anavrin1990** [comment]
@SolidAlloy SolidUtilities has critical bug with GetMainWindowPosition. Dependency doesn't has this method.

**Comment by SolidAlloy** [comment]
Sorry about that, the bug has been fixed, and ClassTypeReference 2.6.4 should be working fine now.
I created the [max-os-position-fix](https://github.com/SolidAlloy/ClassTypeReference-for-Unity/tree/mac-os-position-fix) branch to further investigate the issue you have with the drop-down position.
I added a change there, that initiates the drop-down window with a 100 height instead of 0 (long story short, the height of 1 messes up with the drop-down position on Windows, so 100 should work on both platforms). Please check that the drop-down is at least non-empty now. Please follow these steps to install the package in this branch:
1. Remove SolidUtilities and ClassTypeReference if you have them installed.
2. Package Manager -> Add package from Git URL.
3. Enter "https://github.com/SolidAlloy/SolidUtilities.git#mac-os-position-fix".
4. Enter "https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git#mac-os-position-fix".

Sorry for having to investigate it on your end 🙏 If only I had a Mac to test it on.

As for the X-axis issue, I think it has something to do with resizing inside of AdjustSizeIfNeeded(). I will add more debug logs in _mac-os-position-fix_, and I hope we'll find the root cause soon.

**Comment by Anavrin1990** [comment]
@SolidAlloy 

New versions with new errors =)

![image](https://user-images.githubusercontent.com/25079982/100540150-4a032700-325d-11eb-9c8f-b5c49e4269df.png)

**Comment by Anavrin1990** [comment]
I cached _windowPosition OnCreate and used it after Resize and it works properly.

<img width="1429" alt="Снимок экрана 2020-11-29 в 16 46 32" src="https://user-images.githubusercontent.com/25079982/100540998-cf3d0a80-3262-11eb-9416-2849610e8ce2.png">
<img width="1262" alt="Снимок экрана 2020-11-29 в 16 46 52" src="https://user-images.githubusercontent.com/25079982/100541001-d2d09180-3262-11eb-9691-4cda1718b370.png">
<img width="1120" alt="Снимок экрана 2020-11-29 в 16 47 19" src="https://user-images.githubusercontent.com/25079982/100541003-d3692800-3262-11eb-8de1-b994bc4d0b31.png">

**Comment by SolidAlloy** [comment]
OK, now I checked the code against Unity 2019 and correctly placed preprocessor directives. The plugin should finally work without critical errors in Unity 2019.

The Y axis worked for you before, it was the X axis that had the issue, wasn't it? Did setting the height to 100 inside OnCreate() resolve the empty drop-down issue?

The Y position of the window may change later, so just caching it is not a resolution, unfortunately. If the drop-down is opened too close to the bottom of the screen, there is not enough place for it, so the window is raised so that it has enough height.

However, I see you also set the X position of the window after `this.Resize(height: wantedHeight)`, so this is a hint. I think the X position changes to 0 inside Resize(), and you revert it back with your `positionToAdjust.x = ...` line. First-of-all, I merged two Resize() calls into one inside AdjustSizeIfNeeded(). It will be more efficient and will let us pinpoint the root cause sooner. Can you check the drop-down with the latest commits to the **_mac-os-position-fix_** branches? Does it work as expected, or the X axis still changes to 0?

I added a few debug logs to check the X position of the window during its creation and resizing.

**Comment by Anavrin1990** [comment]
X axis is 0. Height 100 inside OnCreate works properly =)

![image](https://user-images.githubusercontent.com/25079982/100606034-a122fd80-332a-11eb-9fbc-1b9d5e539a13.png)

**Comment by Anavrin1990** [comment]
It looks like ShowAsDropDown kill x position =D

**Comment by SolidAlloy** [comment]
That's weird 😅 
I noticed that an incorrect window X position was being set on the window creation, so I fixed it. Could you get the version with the latest commits from the **_mac-os-position-fix_** branch and check if it resolved the 0 X position issue? If not, I have another solution in mind that I can apply.

**Comment by Anavrin1990** [comment]
It is still zero =)

![image](https://user-images.githubusercontent.com/25079982/100737326-d5afbb80-33f5-11eb-93d0-32836547b535.png)

**Comment by Anavrin1990** [comment]
@SolidAlloy

**Comment by SolidAlloy** [comment]
Hi, I pushed an update to ClassTypeReference in which the window position is set once again during its first Update after the creation. Please checkout ClassTypeReference in the **_max-os-position-fix_** branch and SolidUtilities in the **_master_** branch:
https://github.com/SolidAlloy/SolidUtilities.git
https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git#mac-os-position-fix

Let me know if it worked

**Comment by Anavrin1990** [comment]
Now it has error but after import ChildProperties it works properly! =)

<img width="2184" alt="Снимок экрана 2020-12-03 в 12 33 45" src="https://user-images.githubusercontent.com/25079982/100978652-850aa080-3564-11eb-9974-70d0a9329de1.png">
<img width="2560" alt="Снимок экрана 2020-12-03 в 12 34 26" src="https://user-images.githubusercontent.com/25079982/100978661-8936be00-3564-11eb-93d3-7b73b00de5c3.png">
<img width="1783" alt="Снимок экрана 2020-12-03 в 12 35 26" src="https://user-images.githubusercontent.com/25079982/100978664-8a67eb00-3564-11eb-8b34-faea6ce4aa63.png">
<img width="915" alt="Снимок экрана 2020-12-03 в 12 36 55" src="https://user-images.githubusercontent.com/25079982/100978670-8b008180-3564-11eb-989e-8fd530a14061.png">

**Comment by SolidAlloy** [comment]
Glad to hear it! :) I fixed the error in the sample and merged the fix to master. You can use ClassTypeReference 2.7.0 now

**Comment by Anavrin1990** [comment]
@SolidAlloy Thanks! Good work!
