### ISSUE TITLE
DLL conflicts with Cysharp packages

### ISSUE THREAD

**Issue by Kazkoo** [SolidAlloy/ClassTypeReference-for-Unity#25]
DLL conflicts with Cysharp ZString and ZLogger and Type-References. Both you and Cysharp are including system DLLs in the package and they seem to be of different version, resulting in conflicts.

I made a test in an empty project (2021.1.0b4). Installing ZString OR ZLogger in combination with Type-References results in DLL conflicts. I wrote to them as well but what's your take on this? What is the best solution?

Suggested by SolidAlloy here: https://github.com/SolidAlloy/ClassTypeReference-for-Unity/issues/23#issuecomment-772400009

> The following workaround seems to work:
> 
> 1. Remove System.Buffers.dll and System.Runtime.CompilerServices.Unsafe.dll from the Plugins folder.
> 2. Disable "Auto Reference" and "Validate References" in System.Memory.dll
> 3. In ZString.asmdef, enable "Override References" and add the following DLLs:
> 
> * TypeReferences_System.Buffers.dll
> * TypeReference_System.Runtime.CompilerServices.Unsafe.dll
> * System.Memory.dll
> 
> I tried using both TypeReferences and ZString after that and got no errors in the console. Deleting DLLs in the TypeReferences folder should also work, but it would require making the plugin an embedded package, so deleting DLLs in the Plugins folder is easier.

@Cysharp can you please check on this and suggest your solution? Is there a way to modify your and/or @SolidAlloy packages to avoid conflicts and workarounds? Thanks a lot!

**Comment by SolidAlloy** [comment]
I see Cysharp closed the issue, so I'm closing this one too.

Adding to my previous reply, this is a known issue with Unity - there is no single source of NuGet packages for a project, so each plugin brings its own DLLs which causes conflicts. The best solution as of now would be OpenUPM bringing over some of the most popular NuGet packages to its platform. [It is planned](https://github.com/openupm/openupm/discussions/553).

While it is not supported, I could reference a package [like this](https://openupm.com/packages/com.worldreaver.systemmemory/) instead of bringing in my own DLLs. However, there is a couple of issues associated with it:
1. I haven't seen anyone else use these packages, so it will be necessary to convince other plugin developers to reference them.
2. There are [installation issues](https://github.com/worldreaver/SystemMemory/issues/1) in some of the packages, and the author hasn't resolved them yet.

In this situation, I prefer to keep it as is, and once OpenUPM starts supporting NuGet packages officially, I will switch to dependencies instead of built-in DLLs.

**Comment by Kazkoo** [comment]
Thanks for the info! I was not aware that this is a known issue. I was
under the impression that two openupm packages should not conflict with
each other, as I thought the scope is highly currated.
Thanks for the proposals of how to circumvent the conflicting situations. I
hope the scope will soon get this necessary upgrade.

Martin
