### ISSUE TITLE
UIElements Or Checking When Value Has Changed

### ISSUE THREAD

**Issue by dannymate** [SolidAlloy/ClassTypeReference-for-Unity#34]
So I'm currently using https://github.com/alelievr/NodeGraphProcessor. The nodes use UIElements to draw their inspectors and while it does draw the dropdown field I can't get events via RegisterValueChangeCallback or RegisterCallback. When the field is set I want to auto generate an object of that type.

Do you think it would be possible to create a UIElement implementation (IMGUI and UIElement coexist, whatever's drawing chooses which one it prefers)? I don't mind pitching in, just want to know if it's feasible first.

If not do you know the best way to implement a listener for field changes?

**Comment by dannymate** [comment]
I tried using the TrackPropertyValue which I switched my events over to because it's closer to what I want but still not getting anything. Not sure if this is because the actual Type setting doesn't replace the existing TypeReference so it doesn't note any changes or it just doesn't work for whatever reason there.

**Comment by SolidAlloy** [comment]
Hi, thanks for submitting the issue. I made it so that callbacks are invoked on a VisualElement when the type assigned to the property changes. So you can subscribe via `RegisterValueChangeCallback` and receive callbacks now.

As for `TrackPropertyValue`, it will never be called if you subscribe to the TypeReference property because `TypeReference` is a serializable class. It would be called only if the reference to the class changes, i.e. the instance of `TypeReference` is replaced, but it never happens. Instead, you need to subscribe to the `_typeNameAndAssembly` property:
``` csharp
visualElement.TrackPropertyValue(serializedObject.FindProperty($"{typeRefFieldName}._typeNameAndAssembly"), property => Debug.Log("type changed"));
```

`_typeNameAndAssembly` is a serialized string field that changes when a different type is chosen, so you can track it.
